<a href="https://colab.research.google.com/github/Shanb007/ML_Assigments/blob/master/Assignment0_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
print(sys.version)

3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]


In [ ]:
import site
print(site.getsitepackages())

['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']


In [ ]:
import os
print('PAth:',os.path)

#doubt

PAth: <module 'posixpath' from '/usr/lib/python3.6/posixpath.py'>


In [ ]:
import numpy as np
a = np.random.rand(2,3)
print("Matrix a: ")
print(a)
b = np.random.rand(3,2)
print("Matrix b: ")
print(b)
print('\n')
print("The Dot product:")
print(a.dot(b))

Matrix a: 
[[0.05999579 0.97580095 0.8018232 ]
 [0.72394103 0.5704121  0.46452101]]
Matrix b: 
[[0.92809234 0.87489485]
 [0.04441364 0.63462333]
 [0.70437107 0.05144781]]


The Dot product:
[[0.66380157 0.71300811]
 [1.02441336 1.0192677 ]]


In [ ]:
import numpy as np
sum = np.arange(4).reshape(2,2)
sum = 0 * sum
for i in range(0,6):
  a = np.random.rand(2,3)
  b = np.random.rand(3,2)
  z = a.dot(b)
  sum = sum + z

avg = z/5
print("The average matrix: ")
print(avg)

The average matrix: 
[[0.07391825 0.06049454]
 [0.10577005 0.07398034]]


In [ ]:
import numpy as np
import csv

np.savetxt('file1.csv', avg , fmt= '%f')
c = np.genfromtxt("file1.csv")
t = c.T
print("Transposed Matrix: ")
print(t)




Transposed Matrix: 
[[0.073918 0.10577 ]
 [0.060495 0.07398 ]]


In [ ]:
from scipy import stats
mean_t = t.mean()
print('Mean:',mean_t)
p=t.reshape(4,1)
mode_t = stats.mode(p)
print('Mode:',mode_t)
median_t = np.median(t)
print('Median:',median_t)

Mean: 0.07854075
Mode: ModeResult(mode=array([[0.060495]]), count=array([[1]]))
Median: 0.073949


In [ ]:
row, col = t.shape
for i in range(0, row):
  for j in range(0, col):
    if (i > j):
      print("0",end = " "); 
    else:
      print(t[i][j],end = " " ); 
  print(" ")

0.073918 0.10577  
0 0.07398  


In [ ]:
import csv
col_num = int(input())
with open('file1.csv', 'r') as file:
    read = csv.reader(file , delimiter= ' ')
    for row in read:
      print(row[col_num])

0
0.073918
0.105770


In [ ]:
import csv
import numpy as np

try1 = np.random.randint(4, size=(3,3))
print(try1)
np.savetxt('file2.csv',try1 , fmt= '%i' )
print("Enter the number from above matrix, you want to change: ")
num = str(input())
text = open("file2.csv", "r")
text = ''.join([i for i in text]).replace(num, "A")
x = open("file2.csv","w")
x.writelines(text)
x.close()


with open('file2.csv', 'r') as file:
    read = csv.reader(file)
    for row in read:
      print(row)






[[2 2 2]
 [2 1 2]
 [2 2 2]]
Enter the number from above matrix, you want to change: 
2
['A A A']
['A 1 A']
['A A A']
