<a href="https://colab.research.google.com/github/Shanb007/ML_Assigments/blob/master/Assignment_2_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#part1que1
import pandas as pd
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['wine.csv']))
df.head()

Saving wine.csv to wine (4).csv


Wine  Alcohol  Malic.acid   Ash  ...  Color.int   Hue    OD  Proline
0     1    14.23        1.71  2.43  ...       5.64  1.04  3.92     1065
1     1    13.20        1.78  2.14  ...       4.38  1.05  3.40     1050
2     1    13.16        2.36  2.67  ...       5.68  1.03  3.17     1185
3     1    14.37        1.95  2.50  ...       7.80  0.86  3.45     1480
4     1    13.24        2.59  2.87  ...       4.32  1.04  2.93      735

[5 rows x 14 columns]

In [ ]:
#part1qu2
import numpy as np

scores = df.to_numpy()
np.set_printoptions(precision=3)
scores

array([[   1.  ,   14.23,    1.71, ...,    1.04,    3.92, 1065.  ],
       [   1.  ,   13.2 ,    1.78, ...,    1.05,    3.4 , 1050.  ],
       [   1.  ,   13.16,    2.36, ...,    1.03,    3.17, 1185.  ],
       ...,
       [   3.  ,   13.27,    4.28, ...,    0.59,    1.56,  835.  ],
       [   3.  ,   13.17,    2.59, ...,    0.6 ,    1.62,  840.  ],
       [   3.  ,   14.13,    4.1 , ...,    0.61,    1.6 ,  560.  ]])

In [ ]:
#part1que3
n_rows, n_col = scores.shape
#mean
mean_row_list = []
mean_col_list = []
overall_mean = scores.mean()
for i in range(0, n_rows):
  mean_row_list.append(scores[i].mean())
for j in range(0, n_col):
  mean_col_list.append(scores[:,j].mean())
print('Row-wise mean:')
print(mean_row_list)
print('Column-wise mean:')
print(mean_col_list)
print('Overall mean:', overall_mean)

Row-wise mean:
[89.0, 85.36428571428571, 95.91571428571429, 117.96357142857143, 64.97785714285713, 115.44500000000001, 102.67571428571429, 104.98428571428572, 85.20142857142856, 85.53285714285714, 119.39999999999999, 101.86928571428572, 104.35714285714286, 92.26285714285714, 121.60857142857142, 105.52285714285713, 104.14999999999999, 93.05642857142857, 131.85142857142858, 72.39142857142858, 68.56642857142857, 66.22, 84.84928571428573, 82.92785714285715, 71.10428571428572, 72.42357142857142, 95.67142857142858, 102.00785714285715, 77.01214285714286, 84.46142857142857, 103.28214285714286, 119.84214285714286, 81.82214285714285, 101.62, 89.84571428571428, 76.90071428571427, 74.265, 89.55285714285715, 83.245, 67.19714285714285, 69.02571428571427, 84.23142857142857, 89.20785714285715, 59.74571428571429, 74.60714285714286, 89.14857142857143, 87.32214285714285, 81.42, 87.12214285714286, 101.87714285714286, 92.32285714285715, 100.96000000000001, 96.7942857142857, 110.33357142857143, 87.882857142

In [ ]:
#part1que3
n_rows, n_col = scores.shape
#median
median_row_list = []
median_col_list = []
overall_median = np.median(scores)
for i in range(0, n_rows):
  median_row_list.append(np.median(scores[i]))
for j in range(0, n_col):
  median_col_list.append(np.median(scores[:,j]))
print('Row-wise median:')
print(median_row_list)
print('Column-wise median:')
print(median_col_list)
print('Overall median:', overall_median)


Row-wise median:
[2.9299999999999997, 2.705, 2.99, 3.47, 2.835, 3.06, 2.51, 2.605, 2.825, 3.065, 3.06, 2.375, 2.6799999999999997, 2.955, 3.15, 2.865, 2.76, 2.785, 3.0599999999999996, 3.065, 3.085, 3.085, 2.745, 2.5, 2.61, 2.9400000000000004, 2.895, 2.295, 2.96, 2.49, 2.855, 2.87, 2.5549999999999997, 2.845, 2.59, 2.84, 2.73, 2.48, 2.52, 3.285, 3.2199999999999998, 2.84, 3.4050000000000002, 2.8200000000000003, 3.0, 3.09, 3.3449999999999998, 3.215, 2.75, 2.99, 2.91, 2.795, 3.5, 2.8600000000000003, 2.75, 2.87, 3.1, 2.92, 3.135, 1.885, 2.025, 2.01, 2.05, 2.9850000000000003, 2.115, 2.49, 3.08, 2.0549999999999997, 2.1799999999999997, 2.25, 1.9100000000000001, 2.9050000000000002, 2.12, 3.0949999999999998, 2.715, 1.96, 2.0149999999999997, 2.375, 2.1550000000000002, 2.7, 2.34, 2.365, 2.1, 2.165, 2.465, 2.22, 2.13, 2.3, 2.26, 2.1, 2.135, 2.21, 2.0300000000000002, 2.35, 2.62, 2.55, 2.19, 2.525, 3.145, 2.84, 2.2, 1.95, 2.51, 2.0300000000000002, 2.1, 2.41, 2.075, 2.1399999999999997, 2.219999999999999

In [ ]:
#part1que3
n_rows, n_col = scores.shape
#mode
from scipy import stats
mode_row_list = []
mode_col_list = []
overall_mode = stats.mode(scores)
for i in range(0, n_rows):
  mode_row_list.append(stats.mode(scores[i]))
for j in range(0, n_col):
  mode_col_list.append(stats.mode(scores[:,j]))
print('Row-wise mode:')
print(mode_row_list)
print('Column-wise mode:')
print(median_col_list)
print('Overall mode:', overall_mode)


Row-wise mode:
[ModeResult(mode=array([0.28]), count=array([1])), ModeResult(mode=array([0.26]), count=array([1])), ModeResult(mode=array([0.3]), count=array([1])), ModeResult(mode=array([0.24]), count=array([1])), ModeResult(mode=array([0.39]), count=array([1])), ModeResult(mode=array([0.34]), count=array([1])), ModeResult(mode=array([0.3]), count=array([1])), ModeResult(mode=array([0.31]), count=array([1])), ModeResult(mode=array([0.29]), count=array([1])), ModeResult(mode=array([0.22]), count=array([1])), ModeResult(mode=array([0.22]), count=array([1])), ModeResult(mode=array([0.26]), count=array([1])), ModeResult(mode=array([0.29]), count=array([1])), ModeResult(mode=array([0.43]), count=array([1])), ModeResult(mode=array([0.29]), count=array([1])), ModeResult(mode=array([0.3]), count=array([1])), ModeResult(mode=array([0.33]), count=array([1])), ModeResult(mode=array([0.4]), count=array([1])), ModeResult(mode=array([0.32]), count=array([1])), ModeResult(mode=array([0.17]), count=a

In [ ]:
#part1que3
n_rows, n_col = scores.shape
#standard_deviation
std_row_list = []
std_col_list = []
overall_std = scores.std()
for i in range(0, n_rows):
  std_row_list.append(scores[i].std())
for j in range(0, n_col):
  std_col_list.append(scores[:,j].std())
print('Row-wise Standard Deviation:')
print(mean_row_list)
print('Column-wise Standard Deviation:')
print(mean_col_list)
print('Overall Standard Deviation:', overall_std)

Row-wise Standard Deviation:
[89.0, 85.36428571428571, 95.91571428571429, 117.96357142857143, 64.97785714285713, 115.44500000000001, 102.67571428571429, 104.98428571428572, 85.20142857142856, 85.53285714285714, 119.39999999999999, 101.86928571428572, 104.35714285714286, 92.26285714285714, 121.60857142857142, 105.52285714285713, 104.14999999999999, 93.05642857142857, 131.85142857142858, 72.39142857142858, 68.56642857142857, 66.22, 84.84928571428573, 82.92785714285715, 71.10428571428572, 72.42357142857142, 95.67142857142858, 102.00785714285715, 77.01214285714286, 84.46142857142857, 103.28214285714286, 119.84214285714286, 81.82214285714285, 101.62, 89.84571428571428, 76.90071428571427, 74.265, 89.55285714285715, 83.245, 67.19714285714285, 69.02571428571427, 84.23142857142857, 89.20785714285715, 59.74571428571429, 74.60714285714286, 89.14857142857143, 87.32214285714285, 81.42, 87.12214285714286, 101.87714285714286, 92.32285714285715, 100.96000000000001, 96.7942857142857, 110.33357142857143

In [ ]:
#part2
from scipy.stats import pearsonr
l1 = df['Alcohol']
l2 = df['Proline']
p_corr = pearsonr(l1,l2)
p_corr

(0.6437200371782135, 3.288368689992126e-22)

In [ ]:
#part2
import numpy as np
my_choice = df[['Acl','Ash','Mg','Flavanoids','Proanth']]

df2 = my_choice.copy()
#print(df2.head())
mat = df2.to_numpy()
#print(mat)
cov_mat = np.cov(mat.T)
print('Covarience Matrix:')
print(cov_mat)

Covarience Matrix:
[[ 11.153   0.406  -3.975  -1.172  -0.377]
 [  0.406   0.075   1.123   0.032   0.002]
 [ -3.975   1.123 203.989   2.793   1.933]
 [ -1.172   0.032   2.793   0.998   0.373]
 [ -0.377   0.002   1.933   0.373   0.328]]
