<a href="https://colab.research.google.com/github/Shanb007/ML_Assigments/blob/master/Assignment_1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Part1_ques1
import numpy as np
a1 = np.array(10*[0])
a2 = np.array(10*[1])                
a3 = np.array(10*[5])

print('array with 10 zeros:',a1)
print('array with 10 ones:',a2)
print('array with 10 fives:',a3)

array with 10 zeros: [0 0 0 0 0 0 0 0 0 0]
array with 10 ones: [1 1 1 1 1 1 1 1 1 1]
array with 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Part1_ques2
arr1 = np.arange(10,51,2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#Part1_ques3 if 0 and 1 are not to be included.
c = np.random.rand(3,3)
c

array([[0.98587421, 0.06428336, 0.14275496],
       [0.77469547, 0.87959876, 0.5084854 ],
       [0.79290596, 0.63155931, 0.39013287]])

In [ ]:
#alternative for part1_ques3 if 0 and 1 are to be included in the random array being genrated.
d= np.linspace(0,1,9)
d.resize(3,3)
d

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [ ]:
#Part1_ques4
import numpy as np

np.savetxt('file1.txt', c , fmt= '%f')
a = np.genfromtxt("file1.txt")
a

array([[0.985874, 0.064283, 0.142755],
       [0.774695, 0.879599, 0.508485],
       [0.792906, 0.631559, 0.390133]])

In [ ]:
#part2_ques1
from PIL import Image
import numpy as np
import pandas as pd
import csv
from google.colab import files
from io import BytesIO


uploaded = files.upload()
img = Image.open(BytesIO(uploaded['python.png'])).convert('L')

arr_i = np.array(img)
#print(arr_i)
data = pd.DataFrame(arr_i)
print(data)

f_csv = data.to_csv('python_pic_df.csv')
print("This got stored in the CSV file.")

Saving python.png to python.png
     0    1    2    3    4    5    6    ...  793  794  795  796  797  798  799
0    233  233  232  233  233  233  233  ...  233  232  233  233  232  233  233
1    233  232  233  233  233  233  233  ...  233  233  233  232  233  233  232
2    232  233  233  232  232  233  233  ...  233  233  233  233  233  233  232
3    233  233  233  233  233  233  233  ...  233  233  232  233  233  233  233
4    233  232  233  233  232  233  233  ...  233  233  233  233  233  232  233
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
595  233  233  233  233  233  233  233  ...  233  233  232  233  233  233  233
596  233  232  233  233  232  233  233  ...  233  233  233  233  233  232  233
597  232  233  232  233  233  233  233  ...  233  232  233  233  232  233  233
598  233  233  233  232  233  233  233  ...  233  233  233  233  233  233  232
599  232  232  233  232  233  233  233  ...  233  232  233  232  232  233  233

[600 rows x 800 col

In [ ]:
#part2_ques2
df = data.iloc[:(len(data)-1)]
df = df[df.columns[:-1]]
print(df)
ex_file = df.to_excel('pythonpic_excel.xlsx')
print("This got stored in the Excel file..")

     0    1    2    3    4    5    6    ...  792  793  794  795  796  797  798
0    233  233  232  233  233  233  233  ...  233  233  232  233  233  232  233
1    233  232  233  233  233  233  233  ...  232  233  233  233  232  233  233
2    232  233  233  232  232  233  233  ...  233  233  233  233  233  233  233
3    233  233  233  233  233  233  233  ...  233  233  233  232  233  233  233
4    233  232  233  233  232  233  233  ...  233  233  233  233  233  233  232
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
594  232  233  233  233  232  233  233  ...  233  233  233  233  233  233  233
595  233  233  233  233  233  233  233  ...  233  233  233  232  233  233  233
596  233  232  233  233  232  233  233  ...  233  233  233  233  233  233  232
597  232  233  232  233  233  233  233  ...  233  233  232  233  233  232  233
598  233  233  233  232  233  233  233  ...  233  233  233  233  233  233  233

[599 rows x 799 columns]
This got stored in the Exc

In [ ]:
#part2_ques3
import datetime as dt
today = dt.date.today()
print("Today is:",today)

Today is: 2020-08-23


In [ ]:
#part3
print("Enter DOB in format YYYY-MM-DD:")
dob  = str(input())
dob_dt = dt.datetime.strptime(dob, '%Y-%m-%d').date()
#print(dob_dt)
age = today.year - dob_dt.year
if today.month < dob_dt.month:
  age = age - 1
elif today.month == dob_dt.month and today.day < dob_dt.day:
  age = age - 1

print('Your age:',age,'years')



Enter DOB in format YYYY-MM-DD:
1999-08-27
Your age: 20 years
